[sfputil] add support for sfputil debug tx-output/rx-output {port} enable/disable (#162)
<!--
 Please make sure you've read and understood our contributing guidelines:
 https://github.com/Azure/SONiC/blob/gh-pages/CONTRIBUTING.md

 failure_prs.log skip_prs.log Make sure all your commits include a signature generated with `git commit -s` **

 If this is a bug fix, make sure your description includes "closes #xxxx",
 "fixes #xxxx" or "resolves #xxxx" so that GitHub automatically closes the related
 issue when the PR is merged.

 If you are adding/modifying/removing any command or utility script, please also
 make sure to add/modify/remove any unit tests from the tests
 directory as appropriate.

 If you are modifying or removing an existing 'show', 'config' or 'sonic-clear'
 subcommand, or you are adding a new subcommand, please make sure you also
 update the Command Line Reference Guide (doc/Command-Reference.md) to reflect
 your changes.

 Please provide the following information:
-->

## **Summary of Changes**

### **What I did**
- Added a new `debug.py` module to handle **SFP diagnostics and debugging**.
- Replaced existing **utility methods** with functions from `utilities_common.platform_sfputil_helper`.
- Registered `debug` as a subcommand in `sfputil/main.py`.

### **How I did it**
- Created a new `debug.py` file under `sfputil/`.
- Implemented the `debug` command group with the following subcommands:
 - `loopback`: Configures SFP loopback modes.
 - `tx-output`: Enables or disables TX output.
 - `rx-output`: Enables or disables RX output.
- Used helper functions from `utilities_common.platform_sfputil_helper` for better modularity and maintainability.
- Updated `sfputil/main.py` to integrate the new `debug` command.

### **How to verify it**
UT and deploy changed on a testbed
1. Run the following command to check if `debug` is now available:
 ```sh
 sfputil debug --help
2. sfputil debug tx-output Ethernet0 enable
3. sfputil debug rx-output Ethernet0 disable

```
Usage: sfputil debug [OPTIONS] COMMAND [ARGS]...
Try "sfputil debug --help" for help.

Error: no such option: -h
admin@sonic:~$ sudo sfputil debug --help
Usage: sfputil debug [OPTIONS] COMMAND [ARGS]...

 Group for debugging and diagnostic control commands.

 This command group loads platform-specific utilities and prepares them for
 use in diagnostic commands.

Options:
 --help Show this message and exit.

Commands:
 loopback Set module diagnostic loopback mode.
 rx-output Enable or disable RX output on a port.
 tx-output Enable or disable TX output on a port.
admin@sonic:~$ sudo sfputil debug rx-output --help
Usage: sfputil debug rx-output [OPTIONS] PORT_NAME [enable|disable]

 Enable or disable RX output on a port.

Options:
 --help Show this message and exit.
admin@sonic:~$
```